# Setup
title:               MoonHare
tagline:             ''
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kavindu Santhusa
  url:               https://github.com/Ksengine
  email:             kavindusanthusa@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
